---
- name: core.yml - Archlinux Core Setup
  hosts: all
  become: yes

  tasks:

# ARCH FULL UPDATE  ----------------------------------------------------------

    - name: update arch
      pacman:
        update_cache: yes
        upgrade: yes

# INSTALL VARIOUS PACKAGES  --------------------------------------------------

    - name: Install desktop environment
      pacman:
        update_cache: yes
        name:
          - sway
          - plasma
          - plasma-wayland-session
          - xorg-wayland
          - amd-ucode
          - sddm
          - pipewire
          - wireplumber
          - dolphin
          - kde-connect
          - plasma-systemmonitor
          - nftables 
          - firewalld