---
- name: core.yml - Archlinux Core Setup
  hosts: all
  become: yes

  tasks:

# ARCH FULL UPDATE  ----------------------------------------------------------

    - name: update arch
      pacman:
        update_cache: yes
        upgrade: yes

# INSTALL VARIOUS PACKAGES  --------------------------------------------------

    - name: Install desktop environment
      pacman:
        update_cache: yes
        name:
        # Base programs
          - xorg-xwayland
          - amd-ucode
          - linux-firmware 
          - mesa
          - acpilight
          - sddm
          - iwd
          - networkmanager
        # Necessary Programms and Security
          - kde-connect
          - plasma-systemmonitor
          - nftables 
          - firewalld
          - flatpak
        # Desktop environment
          - hyprland 
          - hyprpaper
          - hyprctl
          - hyprlock
          - hyprpicker
          - waybar
          - wofi
          - dunst
          - wl-clipboard
          - cliphist
          - xdg-desktop-portal-hyprland
          - polkit-kde-agent
          - qt5-wayland
          - qt6-wayland
          - pipewire
          - pipewire-audio
          - pipewire-pulse
          - pipewire-alsa
          - pipewire-jack
          - wireplumber
          - slurp
        # Necessary Programs
          - alacritty
          - dolphin
          - vivaldi
