---
- name: core.yml - Archlinux Core Setup
  hosts: all
  become: yes

  tasks:

# ARCH FULL UPDATE  ----------------------------------------------------------

    - name: update arch
      pacman:
        update_cache: yes
        upgrade: yes

# INSTALL VARIOUS PACKAGES  --------------------------------------------------

    - name: Install desktop environment
      pacman:
        update_cache: yes
        name:
        # Base programs
          - xorg-xwayland
          - amd-ucode
          - linux-firmware 
          - mesa
          - acpilight
          - sddm
          - iwd
          - networkmanager
          - wireless-regdb 
          - power-profiles-daemon
        # Necessary Programms and Security
          - nftables 
          - firewalld
          - flatpak
        # Desktop environment
          - hyprland 
          - hyprpaper
          - hyprctl
          - hyprlock
          - hyprpicker
          - waybar
          - wofi 
          - dunst # notification daemon
          - xdg-desktop-portal-hyprland
          - polkit-kde-agent # authentication agent
          - qt5-wayland
          - qt6-wayland
        # Other Programms for hyprland
          - wl-clipboard
          - cliphist
          - slurp
          - udisks2
          - udiskie
        # Sound
          - pipewire 
          - pipewire-audio
          - pipewire-pulse
          - pipewire-alsa
          - pipewire-jack
          - wireplumber
          - easyeffect
        # Necessary Programs
          - alacritty
          - dolphin
          - vivaldi
          - nano
