---
- name: setup_software.yml - software
  hosts: all
  become: yes

  tasks:

    - name: Install user programs
      pacman:
        update_cache: yes
        name:
          - sudo
          - timeshift
          # Essential
          - vivaldi-ffmpeg-codecs 
          - vlc
          - keepassxc
          - obsidian
          - veracrypt
          - kwallet-pam
          - kdenlive
          - kwalletmanager
          - okular
          - kcalc
          - spectacle
          # Programming
          - code
          - zsh
          - inkscape
          - git
          - python
          - pyenv
          - ffmpeg
          - ruby
          - qmk
          - base-devel
          # Sound + Video
          - easyeffects
          - gwenview
          # Techstuff
          - d-spy
          - kicad
          - snapper
          - snap-pac
          - font-managers 
          - android-udev
          # Gaming
          - discord
          - nextcloud-client 
          - steam
          - lutris 
          - wine
          - winetricks
          - wine-mono
          # Virtualisation
          - podman
          - qemu-full
          - virt-manager
          - libvirt
          - dnsmasq
          - swtpm
          # Terminal-Tools
          - atuin
          - nnn
          - glow
          - ueberzug

    - name: Install dependencies for other programs
      pacman:
        reason: dependency
        name:
        # KiCad
          - kicad-library 
          - kicad-library-3d
        # EasyEffects
          - lsp-plugins-lv2
          - calf 
        # Steam font
          - ttf-liberation 

    - name: Install nnn plugins
      shell: 'sh -c "$(curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs)"'

    - name: Install tmux plugin manager
      shell: 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"'


    - name: Install VSCode extentions
      shell: "code --install-extension {{ item }}"
      with_items:
        - continue.continue
        - gruntfuggly.todo-tree
        - james-yu.latex-workshop
        - jeff-hykin.better-shellscript-syntax
        - llvm-vs-code-extensions.vscode-clangd
        - mechatroner.rainbow-csv
        - mhutchie.git-graph
        - moshfeu.diff-merge
        - ms-azuretools.vscode-docker
        - ms-python.debugpy
        - ms-python.python
        - rust-lang.rust-analyzer
        - yzhang.markdown-all-in-one

# --------------------------------------------
# Install custom Tools not available in pacman
# --------------------------------------------

    - name: Install Flatpak Software
      community.general.flatpak:
        name:
          - com.heroicgameslauncher.hgl
          - com.teamspeak.TeamSpeak
          - com.spotify.Client
          - org.prismlauncher.PrismLauncher
          - com.github.tchx84.Flatseal
          - org.signal.Signal
          - de.bund.ausweisapp.ausweisapp2
          - com.brave.Browser
          - io.podman_desktop.PodmanDesktop
        state: present