---
- name: setup_software.yml - software
  hosts: all
  become: yes

  tasks:

    - name: Install user programs
      pacman:
        update_cache: yes
        name:
          - sudo
          - timeshift
          - code
          - zsh
          - zsh-autosuggestions
          - code
          - inkscape
          - vivaldi-ffmpeg-codecs 
          - vlc
          - ffmpeg
          - obsidian
          - git
          - python 
          - qmk
          - keepassxc
          - discord
          - spotify-launcher
          - nextcloud-client 
          - steam
          - lutris 
          - qemu-full
          - virt-manager
          - libvirt


# --------------------------------------------
# Install custom Tools not available in pacman
# --------------------------------------------

    - name: Get Heroic Games Launcher latest tag 
      github_release:
        user: gogs
        repo: gogs
        action: latest_release
      register: gogs_latest 

    - name: Intall Heroic Games Launcher
      unarchive: 
        src: "https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/Heroic-{{ gogs_latest['tag'].AppImage"
        dest: /opt/bin
        remote_src: true 

    - name: Install Footage (Flathub)
      community.general.flatpak:
        name:
          - io.gitlab.adhami3310.Footage
        state: present
