---
- name: core.yml - Archlinux Setup
  hosts: all
  become: yes

  tasks:
# SYSTEM SETTINGS CHANGES ----------------------------------------------------

    - name: pacman - enable color
      lineinfile:
        path: /etc/pacman.conf
        regexp: '^#Color$'
        line: 'Color'

    - name: pacman - enable ParallelDownloads = 10
      lineinfile:
        path: /etc/pacman.conf
        regexp: '#ParallelDownloads = 10'
        line: 'ParallelDownloads = 10'

    - name: fstab change relatime to noatime
      replace:
        path: /etc/fstab
        regexp: 'relatime'
        replace: 'noatime'

# ARCHLINUX-KEYRING WEEKLY UPDATE  -------------------------------------------

    - name: archlinux-keyring - enable weekly update
      systemd:
        name: archlinux-keyring-wkd-sync.timer
        enabled: yes
        state: started

# CACHE CLEANER SCHEDULED  ---------------------------------------------------

    - name: install pacman-contrib
      pacman:
        name:
          - pacman-contrib

    - name: enable and start weekly cache cleanup paccache timer
      systemd:
        name: paccache.timer
        enabled: yes
        state: started

# LOGROTATE  -----------------------------------------------------------------

    - name: install logrotate
      pacman:
        name:
          - logrotate

    - name: logrotate - enable compression
      lineinfile:
        path: /etc/logrotate.conf
        regexp: '^#compress$'
        line: 'compress'

    - name: enable and start daily logs rotation, cleanup
      systemd:
        name: logrotate.timer
        enabled: yes
        state: started

# HYPRLAND---------------------------------------------------------------------

    - name: copy .myownrc
        copy:
          src: ../dotconfig/hyprland.cfg
          dest: ~/.config/hypr/hyprland.conf
          mode: '0644'


# ZSH ------------------------------------------------------------------------

    - name: change shell
      become: yes
      user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/zsh

    - name: Intall oh-my-zsh 
      become: no
      shell: "curl -fsSL  https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh"

    - name: copy .myownrc
        copy:
          src: ../dotconfig/zsh.cfg
          dest: ~/.zshrc
          mode: '0644'


 # GIT -----------------------------------------------------------------------

    - git_config:
        name: user.email
        scope: global
        value: heumann-a

    - git_config:
        name: user.name
        scope: global
        value: heumann-a

    - git_config:
        name: credential.helper
        scope: global
        value: 'cache --timout=3600'

#  -----------------------------