---
- name: setup_software.yml - software
  hosts: all
  become: yes

  tasks:

    - name: Install user programs
      pacman:
        update_cache: yes
        name:
          - sudo
          - timeshift
          - code
          - zsh
          - code
          - inkscape
          - vivaldi-ffmpeg-codecs 
          - vlc
          - ffmpeg
          - obsidian
          - veracrypt
          - okular
          - gwenview
          - kwallet-pam
          - kdenlive
          - kwalletmanager
          - git
          - python
          - pyenv
          - ruby
          - easyeffects
          - qmk
          - d-spy
          - base-devel
          - kicad
          - snapper
          - snap-pac
          - keepassxc
          - discord
          - nextcloud-client 
          - steam
          - lutris 
          - qemu-full
          - virt-manager
          - libvirt
          - dnsmasq
          - swtpm
          - wine
          - winetricks
          - wine-mono
          - font-managers 
          - android-udev
          - kcalc
          - spectacle
          - podman
          - reflector

    - name: Install dependencies for other programs
      pacman:
        reason: dependency
        name:
          - kicad-library 
          - kicad-library-3d
          - lsp-plugins-lv2
          - calf 
          - ttf-liberation # steam font

    - name: Install VSCode extentions
      shell: "code --install-extension {{ item }}"
      with_items:
        - continue.continue
        - gruntfuggly.todo-tree
        - james-yu.latex-workshop
        - jeff-hykin.better-shellscript-syntax
        - llvm-vs-code-extensions.vscode-clangd
        - mechatroner.rainbow-csv
        - mhutchie.git-graph
        - moshfeu.diff-merge
        - ms-azuretools.vscode-docker
        - ms-python.debugpy
        - ms-python.python
        - rust-lang.rust-analyzer
        - yzhang.markdown-all-in-one

# --------------------------------------------
# Install custom Tools not available in pacman
# --------------------------------------------

    - name: Install Flatpak Software
      community.general.flatpak:
        name:
          - com.heroicgameslauncher.hgl
          - com.teamspeak.TeamSpeak
          - com.spotify.Client
          - org.prismlauncher.PrismLauncher
          - com.github.tchx84.Flatseal
          - org.signal.Signal
          - de.bund.ausweisapp.ausweisapp2
          - com.brave.Browser
        state: present