---
- name: setup_software.yml - software
  hosts: all
  become: yes

  tasks:

    - name: Install user programs
      pacman:
        update_cache: yes
        name:
          - sudo
          - timeshift
          - code
          - zsh
          - code
          - inkscape
          - vivaldi-ffmpeg-codecs 
          - vlc
          - ffmpeg
          - obsidian
          - git
          - python 
          - qmk
          - keepassxc
          - discord
          - nextcloud-client 
          - steam
          - lutris 
          - qemu-full
          - virt-manager
          - libvirt
          - wine
          - winetricks
          - ttf-liberation # steam font

# --------------------------------------------
# Install custom Tools not available in pacman
# --------------------------------------------

    - name: Install Flatpak Software
      community.general.flatpak:
        name:
          - com.heroicgameslauncher.hgl
          - com.teamspeak.TeamSpeak
          - com.spotify.Client
          - org.prismlauncher.PrismLauncher
          - com.github.tchx84.Flatseal
          - io.gitlab.adhami3310.Footage
          - org.signal.Signal
        state: present

