---
- name: core.yml - Archlinux Setup
  hosts: all
  become: yes

  tasks:

# SYSTEM SETTINGS CHANGES ---------------------------------------------------

    - name: pacman - enable color
      lineinfile:
        path: /etc/pacman.conf
        regexp: '^#Color$'
        line: 'Color'

    - name: pacman - enable ParallelDownloads = 10
      lineinfile:
        path: /etc/pacman.conf
        regexp: '#ParallelDownloads = '
        line: 'ParallelDownloads = 10'
        backrefs: yes

    - name: fstab change relatime to noatime
      replace:
        path: /etc/fstab
        regexp: 'relatime'
        replace: 'noatime'

# ARCHLINUX-KEYRING WEEKLY UPDATE  ------------------------------------------

    - name: archlinux-keyring - enable weekly update
      systemd:
        name: archlinux-keyring-wkd-sync.timer
        enabled: yes
        state: started

# POWER DAEMON --------------------------------------------------------------

    - name: Set PPD as active 
      systemd:
        name: powertop
        enabled: yes
        state: started

    - name: Auto-Tune power profile
      become: true
      shell: "powertop --auto-tune"

# CUPS Socket --------------------------------------------------------------

    - name: Set CUPS socket as active 
      systemd:
        name: cups.socket
        enabled: yes
        state: started

# QEMU ----------------------------------------------------------------------

    - name: Set Libvirt for QEMU
      systemd:
        name: libvirtd.service
        enabled: yes
        state: started

    - name: Set DNSMASQ for QEMU disabled
      systemd:
        name: dnsmasq.service
        enabled: no
        state: stopped

    - name: Ensure that default network is active
      community.libvirt.virt_net:
        autostart: true
        state: active
        name: default

              
# WIFI REGDOMAIN--------------------------------------------------------------

- name: Ensure WIFI Domain is set to DE
    lineinfile:
      dest: /etc/conf.d/wireless-regdom
      regexp: '^#\s*WIRELESS_REGDOM.*$'
      line: 'WIRELESS_REGDOM="DE"'

# SLEEP Config ----------------------------------------------------------------

- name: Set Hibernate Delay Secons
    lineinfile:
      dest: /etc/systemd/sleep.conf
        regexp: '#HibernateDelaySec='
        line: 'HibernateDelaySec=10min'


# IWD Backend ---------------------------------------------------------------

  - name: Disable iwd
    systemd:
      name: iwd.service
      enabled: no
      state: stopped

  - name: Creating a file with content
    copy:
      dest: /etc/NetworkManager/conf.d/wifi_backend.conf
      content: |
        [device]
        wifi.backend=iwd


# FIREWALL -------------------------------------------------------------------

  - name: Enable firewalld
    systemd:
      name: firewalld.service
      enabled: yes
      state: started

# LOGROTATE  -----------------------------------------------------------------

    - name: install logrotate
      pacman:
        name:
          - logrotate

    - name: logrotate - enable compression
      lineinfile:
        path: /etc/logrotate.conf
        regexp: '^#compress$'
        line: 'compress'

    - name: enable and start daily logs rotation, cleanup
      systemd:
        name: logrotate.timer
        enabled: yes
        state: started

# HYPRLAND---------------------------------------------------------------------

    - name: copy .myownrc
      copy:
        src: ../dotconfig/hyprland.cfg
        dest: ~/.config/hypr/hyprland.conf
        mode: '0644'


# ZSH ------------------------------------------------------------------------

    - name: change shell
      become: yes
      user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/zsh

    - name: Intall oh-my-zsh 
      become: no
      shell: "curl -fsSL  https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh"

    - name: Intall zsh-autosuggestions
      become: no
      shell: "git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"

    - name: Install zsh-syntax-highlighting
      become: no
      shell: "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting"

    - name: copy .myownrc
      copy:
        src: ../dotconfig/zsh.cfg
        dest: ~/.zshrc
        mode: '0644'


# BLACKARCH-------------------------------------------------------------------

    - name: Download Blackarch.sh
      ansible.builtin.get_url:
        url: https://blackarch.org/strap.sh
        dest: /tmp/strap.sh
        mode: '0555'
        checksum: sha1:26849980b35a42e6e192c6d9ed8c46f0d6d06047

    - name: Install Blackarch
      become: yes
      ansible.builtin.shell: /tmp/strap.sh


# QMK ------------------------------------------------------------------------

    - name: Copy QMK Udev rules
      become: yes
      copy:
        src: ../dotconfig/50-qmk.rules
        dest: /etc/udev/rules.d/50-qmk.rules
        mode: '0644'

 # GIT -----------------------------------------------------------------------

    - git_config:
        name: user.email
        scope: global
        value: heumann-a

    - git_config:
        name: user.name
        scope: global
        value: heumann-a

    - git_config:
        name: credential.helper
        scope: global
        value: 'cache --timout=3600'

 # PYTHON -----------------------------------------------------------------------

    - name: Install pyenv-virtualenvs
      become: no
      shell: "git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv"

 # GROUPS ---------------------------------------------------------------------

- name: Add user to many groups
  ansible.builtin.user:
    name: gungnir
    shell: /bin/bash
    groups: sudo,kvm,libvirt
    append: yes

#  -----------------------------